### PR TITLE
Send isIndexing when calling store.update() from Bucket

### LINKED ISSUE #29: Default storage and bucket update() arity mismatch
On `update()`, the Bucket calls `update()` on the store, but the arity of the two does not match, which means the `callback` argument is not a function, triggering this error:

```
TypeError: callback is not a function
    at BucketStore.update (./node_modules/simperium/lib/simperium/storage/default.js:23:2)
    at Bucket.update (./node_modules/simperium/lib/simperium/bucket.js:44:20)
    at Bucket.Channel.bucket.update (./node_modules/simperium/lib/simperium/channel.js:255:17)
```

Bucket:

```
Bucket.prototype.update = function( id, data, options, callback ) {
	if ( typeof options === 'function' ) {
		callback = options;
	}
	return this.store.update( id, data, callback );
};
```
https://github.com/Simperium/node-simperium/blob/6c401c0cccd909b756df6fce492f88545f2ea656/src/simperium/bucket.js#L27-L32

Default Store:

```
BucketStore.prototype.update = function( id, object, isIndexing, callback ) {
	this.objects[id] = object;
	callback( null, {id: id, data: object, isIndexing: isIndexing} );
};
```

https://github.com/Simperium/node-simperium/blob/6c401c0cccd909b756df6fce492f88545f2ea656/src/simperium/storage/default.js#L13-L16

Note the extra `isIndexing` argument on the Store that the Bucket isn't sending.

### PR DESCRIPTION
**Pull request by nickdaugherty**
`store.update()` has an arity of 4, but we were calling it with an
arity of 3, which means it probably never worked at all (`callback` is
always not a function and triggers an uncaught exception).

Fix arguments to `store.update()`

Fixes #29

### CODE REVIEW

**Comment by nickdaugherty** [comment]
ping @dmsnell / @beaucollins

File: test/simperium/mock_bucket_store.js [hunk 1]
```diff
@@ -15,10 +15,10 @@ BucketStore.prototype.get = function( id, callback ) {
 	} );
 };
 
-BucketStore.prototype.update = function( id, object, callback ) {
+BucketStore.prototype.update = function( id, object, isIndexing, callback ) {
```
Comment (dmsnell) [inline test/simperium/mock_bucket_store.js]: Are we fine using EcmaScript 2015 syntax here?

```js
const noop = () => null;

BucketStore.prototype.update = function( id, object, isIndexing, callback = noop ) {
	this.objects[ id ] = object;

	process.nextTick( callback.bind( null, null, { id, data: object, isIndexing } ) );
};
```

Comment (beaucollins) [inline test/simperium/mock_bucket_store.js]: Definitely. Feel free to make any es6 related changes you want.

File: test/simperium/default_storage_test.js [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+				done();
+			} );
+		} );
+	} );
+
+	it( 'should update with options', function( done ) {
+		var id = 'thing',
+			data = {one: 'two'}
+
+		bucket.update( id, data, {}, function() {
```
Comment (dmsnell) [inline test/simperium/default_storage_test.js]: I'm confused here because the function declaration shows `( id, object, isIndexing, callback )` where I presume `isIndexing` should be a boolean value, but this line calls `( id, object, {}, callback )`.

Is that intentional?

File: test/simperium/default_storage_test.js [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+
+	beforeEach( function() {
+		bucket = new Bucket( 'things', defaultStore );
+	} )
+
+	it( 'should store object update', function( done ) {
+		var id = 'thing',
+			data = {one: 'two'};
+
+		bucket.update( id, data, function() {
```
Comment (dmsnell) [inline test/simperium/default_storage_test.js]: Should this fail here too because of the arity issue you raised?

File: test/simperium/default_storage_test.js (hunk 2 above)
Comment (beaucollins) [inline test/simperium/default_storage_test.js]: It was just an additional argument to test arity specifically as it pertains to #29.

**Comment by dmsnell** [comment]
I had some questions about this until I read above the top lines :panda_face: Looks good to me now :smile:

File: test/simperium/mock_bucket_store.js (hunk 1 above)
Comment (beaucollins) [inline test/simperium/mock_bucket_store.js]: I think the entire project could use another look with an es6 lens.

Originally it was not being transpiled and the biggest changes after adding babel was the es6 `import` syntax.
